services:
  proxy:
    build: ./nginx_container
    container_name: "subtlesolve-proxy"
    restart: always
    ports:
      - "80:80"
    networks:
      - subtlesolve-network
  
  subtlesolve-fe:
    image: rohanj13/subtlesolverepo:react-app-${TAG}
    build: ./subtlesolve_frontend
    container_name: "subtlesolve-fe"
    depends_on:
      - subtlesolve-be
    networks:
      - subtlesolve-network

  subtlesolve-be:
    build: ./backend
    container_name: "subtlesolve-be"
    depends_on:
      - postgres
      - keycloak
    networks:
      - subtlesolve-network

  postgres:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_db_user
      POSTGRES_PASSWORD: password
    networks:
      - subtlesolve-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev
    container_name: "keycloak"
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HEALTH_ENABLED: "true"
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: keycloak_db_user
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    networks:
      - subtlesolve-network


  # keycloak:
  #   image: quay.io/keycloak/keycloak:24.0.4
  #   command: ["start-dev"]
  #   container_name: keycloak
  #   environment:
  #     DB_VENDOR: ${DB_VENDOR}
  #     DB_ADDR: database
  #     DB_PORT: 5432
  #     DB_SCHEMA: public
  #     DB_DATABASE: "keycloak_db"
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     KEYCLOAK_USER: ${KEYCLOAK_USER}
  #     KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
  #     KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
  #     KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
  #     KC_PROXY_MODE: edge
  #     KC_METRICS_ENABLED: true
  #     KC_HTTP_ENABLED: true
  #   ports:
  #     - "8089:8080"
  #   depends_on:
  #     - postgresql
  #   restart: always
  #   links: 
  #     - postgresql
  #   networks:
  #     - subtlesolve-network

  # postgresql:
  #   image: postgres:14
  #   environment:
  #   # add multiple schemas
  #     # POSTGRES_MULTIPLE_DATABASES: ${DB_DATABASE},${KEYCLOAK_DATABASE}
  #     POSTGRES_DB: ${DB_DATABASE}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     # POSTGRES_KEYCLOAK_USER: ${KEYCLOAK_USER}
  #     # POSTGRES_KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
  #     # POSTGRES_DB2: ${KEYCLOAK_DATABASE}
  #   hostname: local
  #   restart: always
  #   volumes:
  #     - ./db-data:/var/lib/postgresql/data/
  #     - ./sql:/docker-entrypoint-initdb.d/:ro
  #     # - ./sql/access_attempt.sql:/docker-entrypoint-initdb.d/A.sql
  #     # - ./sql/bceid.sql:/docker-entrypoint-initdb.d/B.sql
  #     # - ./sql/lookup_activitytype.sql:/docker-entrypoint-initdb.d/C.sql
  #     # - ./sql/lookup_gender_pronoun.sql:/docker-entrypoint-initdb.d/D.sql
  #     # - ./sql/client.sql:/docker-entrypoint-initdb.d/E.sql
  #   ports: 
  #     - "5439:5432"
  #   networks:
  #     - subtlesolve-network
#   mongodb:
#     image: mongodb/mongodb-community-server:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - subtlesolve_data:/data/db
#     environment:
#       - MONGODB_INITDB_ROOT_USERNAME=root
#       - MONGODB_INITDB_ROOT_PASSWORD=example
#       - MONGO_INITDB_DATABASE=subtlesolvedb

volumes:
  postgres_data:
    driver: local

networks:
  subtlesolve-network:
    name: subtlesolve-network
    driver: bridge
