services:
  proxy:
    build: ./nginx_container
    container_name: "subtlesolve-proxy"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - subtlesolve-network
    volumes:
      - ./etc/ssl/cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./etc/ssl/key.pem:/etc/nginx/ssl/key.pem:ro
  
  subtlesolve-fe:
    image: rohanj13/subtlesolverepo:react-app-${TAG}
    build: ./subtlesolve_frontend
    container_name: "subtlesolve-fe"
    depends_on:
      - subtlesolve-be
    networks:
      - subtlesolve-network

  subtlesolve-be:
    build: ./backend
    container_name: "subtlesolve-be"
    depends_on:
      - postgres
      - keycloak
    networks:
      - subtlesolve-network

  postgres:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_db_user
      POSTGRES_PASSWORD: password
    networks:
      - subtlesolve-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: start --optimized
    container_name: "keycloak"
    environment:
      KC_HOSTNAME: subtlesolve.org
      KC_HOSTNAME_PORT: 8443
      KC_HTTPS_PORT: 8443
      KC_HTTP_PORT: 8080
      KC_HTTPS_CERTIFICATE_FILE: "/etc/x509/https/cert.pem"
      KC_HTTPS_CERTIFICATE_KEY_FILE: "/etc/x509/https/key.pem"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: keycloak_db_user
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./etc/ssl/cert.pem:/etc/x509/https/cert.pem:ro
      - ./etc/ssl/key.pem:/etc/x509/https/key.pem:ro
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - subtlesolve-network

volumes:
  postgres_data:
    driver: local

networks:
  subtlesolve-network:
    name: subtlesolve-network
    driver: bridge
