services:
  proxy:
    build: ./nginx_container
    container_name: "subtlesolve-proxy"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - subtlesolve-network
    volumes:
      - web-root:/usr/share/nginx/html
      - ./nginx_container/:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - subtlesolve-fe
      - subtlesolve-be

  subtlesolve-fe:
    image: rohanj13/subtlesolverepo:react-app-${TAG}
    build: ./subtlesolve_frontend
    container_name: "subtlesolve-fe"
    depends_on:
      - subtlesolve-be
    networks:
      - subtlesolve-network

  subtlesolve-be:
    image: rohanj13/subtlesolverepo:spring-boot-app-${TAG}
    build: ./backend
    container_name: "subtlesolve-be"
    depends_on:
      - postgres
      - keycloak_container
    networks:
      - subtlesolve-network

  postgres:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_db_user
      POSTGRES_PASSWORD: password
    networks:
      - subtlesolve-network

  keycloak_container:
    image: rohanj13/subtlesolverepo:latest
    build: ./keycloak_container
    command: start-dev
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - subtlesolve-network

volumes:
  postgres_data:
    driver: local
  certbot-etc:
  certbot-var:
  web-root:

networks:
  subtlesolve-network:
    name: subtlesolve-network
    driver: bridge
